//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IK_Departman
    {
        public int DepartmanID { get; set; }
        public string DepartmanIsim { get; set; }
        public Nullable<int> Departman_No { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<bool> Calısmadurumu { get; set; }
    }
}
