//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IK_Rol
    {
        public int RolId { get; set; }
        public string RolIsim { get; set; }
    }
}
