//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maliye
    {
        public int MaliyeID { get; set; }
        public string Urun { get; set; }
        public Nullable<int> maliyet { get; set; }
        public Nullable<int> satis { get; set; }
        public Nullable<int> kar { get; set; }
        public Nullable<bool> Aktiflik { get; set; }
        public Nullable<bool> CalismaDurumu { get; set; }
    }
}
