//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajlarView_Model
    {
        public Nullable<int> MesajGonderenDepartman { get; set; }
        public string Mesaj { get; set; }
        public string MesajAlanKişi { get; set; }
        public Nullable<int> MesajAlanDepartman { get; set; }
        public string MesajGonderenKisi { get; set; }
        public int MesajID { get; set; }
        public int DepartmanID { get; set; }
        public string DepartmanIsim { get; set; }
    }
}
