//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbIKProjeEntities : DbContext
    {
        public DbIKProjeEntities()
            : base("name=DbIKProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IK_Duyuru> IK_Duyuru { get; set; }
        public virtual DbSet<IK_Mesaj> IK_Mesaj { get; set; }
        public virtual DbSet<IK_Personel> IK_Personel { get; set; }
        public virtual DbSet<IK_Rol> IK_Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<MesajlarView_Model> MesajlarView_Model { get; set; }
        public virtual DbSet<Personel_departman_rol_model_view> Personel_departman_rol_model_view { get; set; }
        public virtual DbSet<View_Mesajlar> View_Mesajlar { get; set; }
        public virtual DbSet<View_PersonelDepartman> View_PersonelDepartman { get; set; }
        public virtual DbSet<IK_Departman> IK_Departman { get; set; }
        public virtual DbSet<Maliye> Maliye { get; set; }
        public virtual DbSet<Dokumanlar> Dokumanlar { get; set; }
        public virtual DbSet<View_DOKUMANLARDEPARTMANLAR> View_DOKUMANLARDEPARTMANLAR { get; set; }
    }
}
