//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsanKaynaklarıProje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_DOKUMANLARDEPARTMANLAR
    {
        public int DokumanID { get; set; }
        public string DokumanGonderenKisi { get; set; }
        public string DokumanGonderenDepartman { get; set; }
        public Nullable<int> DokumanGelenDepartman { get; set; }
        public string Dokuman { get; set; }
        public string DokumanAcıklama { get; set; }
        public int DepartmanID { get; set; }
    }
}
